/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Conexao.ConexaoRel;
import DAO.EstoqueDao;
import DAO.ProdutoDao;
import DAO.SaidaDao;
import DAO.VendaDao;
import DAO.VendedorDao;
import Entidades.Cliente;
import Entidades.Estoque;

import Entidades.Produto;
import Entidades.Saida;
import Entidades.Venda;
import Entidades.Vendedor;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 ***********************************************************
 * ------------- ..::Danilo Alves Oliveira::.. ------------- *
 * **********************************************************
 *
 *
 */
//<editor-fold defaultstate="collapsed" desc="Departamento de Sistemas Desktop">
//</editor-fold>
//<editor-fold defaultstate="collapsed" desc="Tecnologia Java SE">
//</editor-fold>
public class SaidaVenda extends javax.swing.JFrame {

    List<Venda> venda;
    DefaultListModel dlista;
    DefaultListModel dlistam;
    int idcliente;

    DefaultTableModel tmVenda = new DefaultTableModel(null, new String[]{"Produto", "Preço (R$)", "Qtd", "Total (R$)"});
    ListSelectionModel lsmVenda;
    Produto produto;
    List<Vendedor> vendedores;
    int idnota = 0;

    char l;
    int mais = -1;//para verificar se já clicou na seta para baixo
    int contr = 1;//para controlar quando o usuário percorre o produto na lista
    int ilistp = -1;//índice para referenciar a posição selecionada da lista com a lista <produto> 
    int qtd = 0;//para contar a quantidade de produtos vendidos
    int contrenter = 0;
    int tipo = 0;
    boolean orcamento = false;
    int la = 0;//para verificar se clicou no Ctrl

    public SaidaVenda() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("Realizar Venda - SGE");
        ImageIcon imagemTituloJanela = new ImageIcon(getClass().getResource("/Imagens/icon-controle-de-estoqu.png"));
        setIconImage(imagemTituloJanela.getImage());

        //inicializa a lista vendas
        venda = new ArrayList<Venda>();

        PreencherVendedores();

        //impede a edição de alguns campos
        jTValor.setEditable(false);
        jTEndereco.setEditable(false);
        jLQtd.setVisible(false);
        try {
            //Para mostrar o id dessa nova nota
            SaidaDao ndao = new SaidaDao();
            idnota = ndao.getIdUltimaNota();
            idnota++;
            jLNVenda.setText("Venda Nº:" + idnota);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao acessar o banco! \n\r ERRO:" + ex, "..: SGE :..", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTProduto = new javax.swing.JTextField();
        jLNVenda = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTValor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTPreco = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTEndereco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTQtd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jTQtd_est = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVendas = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLQtd = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTTotalg = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Realizar Venda");

        jPanel2.setBackground(new java.awt.Color(0, 131, 73));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dados do cliente:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Produto:");

        jTProduto.setEditable(false);
        jTProduto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTProdutoFocusLost(evt);
            }
        });
        jTProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProdutoMouseClicked(evt);
            }
        });
        jTProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTProdutoActionPerformed(evt);
            }
        });
        jTProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTProdutoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTProdutoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTProdutoKeyTyped(evt);
            }
        });

        jLNVenda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLNVenda.setForeground(new java.awt.Color(255, 255, 255));
        jLNVenda.setText("Venda Nº:33333");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor (R$):");

        jTValor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTValorFocusGained(evt);
            }
        });
        jTValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTValorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTValorKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Preço(R$):");

        jTPreco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTPreco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dados da venda:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cliente:");

        jTCliente.setEditable(false);
        jTCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClienteMouseClicked(evt);
            }
        });
        jTCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTClienteKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Endereço:");

        jTEndereco.setEditable(false);
        jTEndereco.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTEnderecoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTEnderecoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTEnderecoKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Quant.:");

        jTQtd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTQtd.setText("1");
        jTQtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTQtdFocusLost(evt);
            }
        });
        jTQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTQtdActionPerformed(evt);
            }
        });
        jTQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTQtdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTQtdKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Vendedor:");

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox2KeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Quant. em estoque:");

        jTQtd_est.setEditable(false);
        jTQtd_est.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTQtd_est.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTQtd_estFocusLost(evt);
            }
        });
        jTQtd_est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTQtd_estActionPerformed(evt);
            }
        });
        jTQtd_est.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTQtd_estKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTQtd_estKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTProduto)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTQtd_est, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTValor, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTEndereco)
                            .addComponent(jTCliente)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLNVenda)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNVenda)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTQtd_est, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 131, 73));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/disk.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jButton1)
                .addGap(48, 48, 48)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 131, 73));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTVendas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTVendas.setModel(tmVenda);
        jTVendas.setSelectionBackground(new java.awt.Color(0, 131, 73));
        jTVendas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmVenda = jTVendas.getSelectionModel();
        lsmVenda.addListSelectionListener(new ListSelectionListener() { public void valueChanged(ListSelectionEvent e) { if (! e.getValueIsAdjusting()){ jTTabelaLinhaSelecionada(jTVendas); } }
        });
        jTVendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTVendasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTVendas);

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/chec2.png"))); // NOI18N
        jButton3.setText("Finalizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jButton4.setText("Remover");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jLQtd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLQtd.setForeground(new java.awt.Color(255, 255, 255));
        jLQtd.setText("jLabel13");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total Geral...:");

        jTTotalg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jCheckBox1.setBackground(new java.awt.Color(0, 131, 73));
        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Gerar Nota");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLQtd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTTotalg, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jCheckBox1))
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jCheckBox1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTTotalg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLQtd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Ctrl+C = adicionar um Cliente.");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Ctrl+F = Finalizar a Venda.");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Ctrl+P = adicionar um produto.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProdutoKeyPressed
        EventoChamarPoduto(evt);
    }//GEN-LAST:event_jTProdutoKeyPressed

    private void jTProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProdutoKeyTyped

    }//GEN-LAST:event_jTProdutoKeyTyped

    private void jTProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProdutoKeyReleased

    }//GEN-LAST:event_jTProdutoKeyReleased

    public void CalcularValorUnid() {
        double valor = Double.parseDouble(jTPreco.getText()) * Double.parseDouble(jTQtd.getText());
        DecimalFormat num = new DecimalFormat("0.00");
        jTValor.setText((num.format(valor)) + "");
        jTValor.setText(jTValor.getText().replace(",", "."));
    }
    private void jTClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClienteKeyPressed
        EventoChamarPoduto(evt);
    }//GEN-LAST:event_jTClienteKeyPressed

    private void jTClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClienteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTClienteKeyReleased

    private void jTClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTClienteKeyTyped

    private void jTEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTEnderecoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEnderecoKeyPressed

    private void jTEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTEnderecoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEnderecoKeyReleased

    private void jTEnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTEnderecoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEnderecoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdicionarP();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTProdutoFocusLost

    }//GEN-LAST:event_jTProdutoFocusLost
    int contfocus = 0;
    private void jTQtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTQtdFocusLost

    }//GEN-LAST:event_jTQtdFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jTVendas.getSelectedRow() != -1) {
            double tot = venda.get(jTVendas.getSelectedRow()).getPreco();
            DecimalFormat num = new DecimalFormat("0.00");
            jTTotalg.setText(num.format((Double.parseDouble(jTTotalg.getText()) - tot)) + "");
            jTTotalg.setText(jTTotalg.getText().replace(",", "."));
            venda.remove(jTVendas.getSelectedRow());
            atualizarTabela(venda);
            qtd--;
            jLQtd.setText(qtd + " Inten(s)");
            if (qtd == 0) {
                jLQtd.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTValorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTValorKeyReleased

    private void jTQtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTQtdKeyReleased
        if (evt.getKeyCode() == 10) {
            if (!jTQtd.getText().equals("")) {
                contrenter = 1;

                //calcula o valor do prodto com essa área
                double valor = Double.parseDouble(jTPreco.getText()) * Double.parseDouble(jTQtd.getText());
                DecimalFormat num = new DecimalFormat("0.00");
                jTValor.setText(num.format(valor) + "");
                jTValor.setText(jTValor.getText().replace(",", "."));
                AdicionaVenda();
            }

        }
    }//GEN-LAST:event_jTQtdKeyReleased

    private void jTQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTQtdActionPerformed

    private void jTQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTQtdKeyPressed

    }//GEN-LAST:event_jTQtdKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FinalizarTotal();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClienteMouseClicked
        BuscarCliente b = new BuscarCliente();
        b.SetVenda(this);
        b.SetTipo(0);
        b.show();
        jTCliente.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTClienteMouseClicked

    private void jTProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTProdutoActionPerformed

    }//GEN-LAST:event_jTProdutoActionPerformed

    private void jTProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProdutoMouseClicked
        BuscarProduto b = new BuscarProduto();
        b.SetSaidaVenda(this);
        b.SetTipo(1);
        b.show();
        jTProduto.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTProdutoMouseClicked

    private void jTQtd_estFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTQtd_estFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTQtd_estFocusLost

    private void jTQtd_estActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTQtd_estActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTQtd_estActionPerformed

    private void jTQtd_estKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTQtd_estKeyPressed
        EventoChamarPoduto(evt);
    }//GEN-LAST:event_jTQtd_estKeyPressed

    private void jTQtd_estKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTQtd_estKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTQtd_estKeyReleased

    private void jTValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTValorFocusGained
        CalcularValor();
    }//GEN-LAST:event_jTValorFocusGained

    private void jComboBox2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox2KeyPressed
        EventoChamarPoduto(evt);
    }//GEN-LAST:event_jComboBox2KeyPressed

    private void jTValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTValorKeyPressed

    }//GEN-LAST:event_jTValorKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        EventoChamarPoduto(evt);
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        EventoChamarPoduto(evt);
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        EventoChamarPoduto(evt);
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTVendasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTVendasKeyPressed
        EventoChamarPoduto(evt);
    }//GEN-LAST:event_jTVendasKeyPressed

    public void FinalizarTotal() {
        if (venda.size() > 0) {
            Finalizar();
            jTTotalg.setText("");
            jLQtd.setVisible(false);
            qtd = 0;
            if (jCheckBox1.isSelected()) {
                relatorio();
            }
            try {

                //Para mostrar o id dessa nova nota
                SaidaDao ndao = new SaidaDao();
                idnota = ndao.getIdUltimaNota();
                idnota++;
                jLNVenda.setText("Venda Nº:" + idnota);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao acessar o banco! \n\r ERRO:" + ex, "..: SGE :..", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você precisa realizar uma venda antes de finalizar.", "SGE", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void AdicionarP() {
        if (tipo == 0) {
            if (Verifica()) {
                if (jComboBox2.getSelectedIndex() != -1) {
                    CalcularValor();
                    if (Integer.parseInt(jTQtd.getText()) <= Integer.parseInt(jTQtd_est.getText())) {
                        AdicionaVenda();
                    } else {
                        JOptionPane.showMessageDialog(null, "A quantidade informada não pode ser maior que a de estoque.", "..: SGE :..", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "É preciso selecionar um vendedor.", "..: SGE :..", JOptionPane.WARNING_MESSAGE);
                }
            }
        } else {
            if (Verifica2()) {
                AdicionaVenda();
            }
        }
    }

    public void CalcularValor() {
        try {
            int d = Integer.parseInt(jTQtd.getText());
            jTQtd.setText(d + "");

            //calcula o valor do prodto com essa área
            double valor = Double.parseDouble(jTPreco.getText()) * Double.parseDouble(jTQtd.getText());
            DecimalFormat num = new DecimalFormat("0.00");
            jTValor.setText(num.format(valor) + "");
            jTValor.setText(jTValor.getText().replace(",", "."));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "A Quantidade esta inválida.", "..: SGE :..", JOptionPane.WARNING_MESSAGE);
            jTQtd.setText("");
            jTValor.setText("");
            jTQtd.requestFocus();
        }
    }

    private Cliente cliente;

    public void SetCliente(Cliente cliente) {
        this.cliente = cliente;
        jTCliente.setText(cliente.getNome());
        jTEndereco.setText(cliente.getEndereco());
        idcliente = this.cliente.getId();
    }

    //metodo para setar o produto que foi escolhido
    public void SetProduto(Produto produto) {

        jTProduto.setText(produto.getProduto());
        jTPreco.setText(produto.getPreco() + "");

        try {
            //busca a qtd desse produto em estoque
            EstoqueDao edao = new EstoqueDao();
            Estoque estoque = edao.GetEstoque(produto.getId());
            if (estoque == null) {
                Estoque e = new Estoque();
                e.setId_p(produto.getId());
                e.setQtd(0);
                edao.adiciona(e);

                estoque = edao.GetEstoque(produto.getId());
            }
            jTQtd_est.setText(estoque.getQtd() + "");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro!" + ex, "..: SGE :..", JOptionPane.ERROR_MESSAGE);
        }

        this.produto = produto;
        jTQtd_est.requestFocus();
    }

    //adiciona na lista a venda do produto
    public void AdicionaVenda() {

        Venda v = new Venda();
        v.setId_p(produto.getId());
        v.setPreco(Double.parseDouble(jTValor.getText()));
        v.setQtd(Integer.parseInt(jTQtd.getText()));
        v.setValor_p(Double.parseDouble(jTPreco.getText()));

        venda.add(v);
        atualizarTabela(venda);

        jTValor.setText(jTValor.getText().replace(",", "."));

        double tot = Double.parseDouble(jTValor.getText());
        double tacu = 0;
        if (!jTTotalg.getText().equals("")) {
            jTTotalg.setText(jTTotalg.getText().replace(",", "."));
            tacu = Double.parseDouble(jTTotalg.getText());
        }
        DecimalFormat num = new DecimalFormat("0.00");
        jTTotalg.setText((num.format(tot + tacu)) + "");
        jTTotalg.setText(jTTotalg.getText().replace(",", "."));
        qtd++;
        jLQtd.setText(qtd + " Iten(s)");
        jLQtd.setVisible(true);

        JOptionPane.showMessageDialog(null, "Produto adicionado a venda!", "..: SGE :..", JOptionPane.INFORMATION_MESSAGE);
        Limpar();
    }

    public boolean Verifica() {
        return VerificarCampo(jTCliente, "Cliente") && VerificarCampo(jTProduto, "Produto") && VerificarCampo(jTQtd, "Qtd");
    }

    public boolean Verifica2() {
        return VerificarCampo(jTCliente, "Cliente") && VerificarCampo(jTProduto, "Produto") && VerificarCampo(jTQtd, "Qtd");
    }

    //metodo para veificar o campo se está vazio e colorir o background caso não esteja
    public boolean VerificarCampo(final JTextField campo, String nome) {
        if (campo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo " + nome + " não pede ser vazio!", "..: SGE :..", JOptionPane.WARNING_MESSAGE);
            campo.setBackground(new Color(255, 51, 51));
            campo.requestFocus();

            campo.addKeyListener(new KeyListener() {

                @Override
                public void keyTyped(KeyEvent ke) {
                    //Não utilizado
                }

                @Override
                public void keyPressed(KeyEvent ke) {
                    if (campo.getBackground() != Color.WHITE) {
                        campo.setBackground(Color.WHITE);
                    }
                }

                @Override
                public void keyReleased(KeyEvent ke) {
                    //Não utilizado
                }
            });
            return false;
        } else {
            return true;
        }
    }

    //método que limpa os campos para a venda de outro produto
    public void Limpar() {
        jTPreco.setText("");
        jTProduto.setText("");
        jTQtd_est.setText("");
        jTValor.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaidaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaidaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaidaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaidaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SaidaVenda().setVisible(true);
        });
    }

    private void atualizarTabela(List<Entidades.Venda> venda) {

        while (tmVenda.getRowCount() > 0) {
            tmVenda.removeRow(0);
        }

        String[] linha = new String[]{null, null, null, null};

        for (int i = 0; i < venda.size(); i++) {
            tmVenda.addRow(linha);
            String produto = "";
            try {
                //Pega o produto com o id na lista da venda
                ProdutoDao dao = new ProdutoDao();
                Produto p = dao.GetProduto(venda.get(i).getId_p());
                produto = p.getProduto();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao acessar o banco! \n\r ERRO:" + ex, "..: SGE :..", JOptionPane.ERROR_MESSAGE);
            }

            tmVenda.setValueAt(produto, i, 0);
            tmVenda.setValueAt(venda.get(i).getValor_p(), i, 1);
            tmVenda.setValueAt(venda.get(i).getQtd(), i, 2);
            tmVenda.setValueAt(venda.get(i).getPreco(), i, 3);
        }
    }

    private void jTTabelaLinhaSelecionada(JTable tabela) {

    }

    //metodo para calcular a área apartir do tamanho
    public double CalculaArea(String tamanho) {
        double h = (Double.parseDouble(tamanho.split("x")[0])) / 100;
        double w = (Double.parseDouble(tamanho.split("x")[1])) / 100;

        return h * w;
    }

    //metodo para preencher o combobox dos vendedores
    public void PreencherVendedores() {
        try {
            VendedorDao a = new VendedorDao();
            vendedores = a.getLista("");
            for (int y = 0; y < vendedores.size(); y++) {
                jComboBox2.addItem(vendedores.get(y).getNome());
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o banco! \n\r ERRO:" + ex, "..: SGE :..", JOptionPane.ERROR_MESSAGE);
        }
    }

    //Cria o relatorio da nota
    private void relatorio(int idnota) {
        Date data = new Date();

        int ano = data.getYear() + 1900;
        int dia = data.getDate();
        int mes = data.getMonth() + 1;
        String dias = null, mess = null;
        if (dia < 10) {
            dias = "0" + dia;
        } else {
            dias = "" + dia;
        }
        if (mes < 10) {
            mess = "0" + mes;
        } else {
            mess = "" + mes;
        }
        String nome = "Orçamento" + idnota + " DATA" + dias + "-" + mess + "-" + ano;
        String arquivo = nome;

        ConexaoRel con = new ConexaoRel();

//diretorio que vai salvar
        File dir = new File("c:/FARelatorios/Orcamento");
        if (!dir.exists()) {
            if (dir.mkdir()) {

            } else {

            }
        }
        File l = new File("c:/FARelatorios/Orcamento/");
        l.mkdir();

        String MostrarRelatorio;
        String path = "c:/FARelatorios/Orcamento/";
        try {
            con.conecta();
            con.executeSQL("select nota.*, produto.*, venda.*, cliente.*, pdf.* from  nota, produto, venda, cliente, pdf where nota.id=" + idnota + " and nota.id=venda.id_n and venda.id_p=produto.id and nota.id_c=cliente.id and pdf.id_n=" + idnota + ";");

            JRResultSetDataSource jrRS = new JRResultSetDataSource(con.resultset);
            //referencia o jasper
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("/Jasper/Nota.jasper"), new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            jv.setTitle("Nota Fiscal - F.A Vidraçaria");
            //jv.setIconImage(new ImageIcon(getClass().getResource("/Imagens/1349387239_gems.jpg")).getImage());
            jv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            // JasperViewer.viewReport(jp,true);
            File arq = new File(path + arquivo + ".pdf");
            if (arq.exists()) {
                int result = JOptionPane.showConfirmDialog(null, "O relatório " + arquivo + ".pdf já existe.\n Dezeja substitui-lo?", "..: SGE :..", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_NO_OPTION) {
                    JasperExportManager.exportReportToPdfFile(jp, path + arquivo + ".pdf");
                    MostrarRelatorio = path + arquivo + ".pdf";
                    JOptionPane.showMessageDialog(null, "Operação Realizada com sucesso!\n Salvo em: " + path + arquivo + ".pdf", "..: SGE :..", JOptionPane.INFORMATION_MESSAGE);
                    try {
                        Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL " + MostrarRelatorio);
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(null, "Erro ao acessar arquivo! \n\r ERRO:" + e.getStackTrace(), "..: SGE :..", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {

                JasperExportManager.exportReportToPdfFile(jp, path + arquivo + ".pdf");
                MostrarRelatorio = path + arquivo + ".pdf";
                JOptionPane.showMessageDialog(null, "Operação Realizada consucesso!\n Salvo em: " + path + arquivo + ".pdf", "..: SGE :..", JOptionPane.INFORMATION_MESSAGE);
                try {
                    Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL " + MostrarRelatorio);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Erro ao acessar arquivo! \n\r ERRO:" + e.getMessage(), "..: SGE :..", JOptionPane.ERROR_MESSAGE);
                }

            }

            //   JasperViewer jv = new JasperViewer(jp, false);
            //  jv.setVisible(true);
            //  jv.setTitle("Lista Contatos");
            //  jv.setIconImage(new ImageIcon(getClass().getResource("/Icones/vista (18).png")).getImage());
        } catch (Exception erro) {

            JOptionPane.showMessageDialog(null, "Erro!" + erro, "..: SGE :..", JOptionPane.INFORMATION_MESSAGE);

        }
    }

    //Metodo de Finalizar
    public void Finalizar() {
        if (VerificaEstoque()) {
            try {

                SimpleDateFormat fo = new SimpleDateFormat("yyyy-MM-dd");
                SaidaDao dao = new SaidaDao();
                Saida n = new Saida();

                Date d = new Date();
                n.setId_c(idcliente);

                n.setTotal(Double.parseDouble(jTTotalg.getText()));
                n.setData(fo.format(d));
                n.setId_fun(vendedores.get(jComboBox2.getSelectedIndex()).getId_vendedor());

                dao.adiciona(n);
                int idnota = dao.getIdUltimaNota();

                //adiciona o id da nota para as vendas
                for (int i = 0; i < venda.size(); i++) {
                    venda.get(i).setId_s(idnota);
                }

                //inicia o cadastro as vendas
                VendaDao vd = new VendaDao();
                for (int i = 0; i < venda.size(); i++) {
                    vd.adiciona(venda.get(i));
                }

                ProdutoDao pdao = new ProdutoDao();
                EstoqueDao edao = new EstoqueDao();
                for (int i = 0; i < venda.size(); i++) {
                    Produto p = pdao.GetProduto(venda.get(i).getId_p());
                    Estoque e = edao.GetEstoque(p.getId());

                    int sub = e.getQtd() - venda.get(i).getQtd();
                    e.setQtd(sub);
                    edao.altera(e);
                    venda.remove(venda.get(i));
                    i = i - 1;
                }

                JOptionPane.showMessageDialog(null, "Saída de estoque cadastrada com sucesso.", "SGE", JOptionPane.INFORMATION_MESSAGE);
                atualizarTabela(venda);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro!" + ex, "..: SGE :..", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public boolean VerificaEstoque() {
        boolean r = true;
        try {
            ProdutoDao pdao = new ProdutoDao();
            EstoqueDao edao = new EstoqueDao();
            for (int i = 0; i < venda.size(); i++) {
                Produto p = pdao.GetProduto(venda.get(i).getId_p());
                Estoque e = edao.GetEstoque(p.getId());

                int sub = e.getQtd() - venda.get(i).getQtd();
                if (sub < 0) {
                    r = false;
                    JOptionPane.showMessageDialog(null, "A quantidade de " + p.getProduto().toUpperCase() + " \n\r em estoque não é suficiente.", "SGE", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro!" + ex, "..: SGE :..", JOptionPane.ERROR_MESSAGE);
        }
        return r;
    }

    public void EventoChamarPoduto(KeyEvent evt) {
        if (evt.getKeyCode() == 17) {
            la = 1;
        }

        //Para adicionar um cliente
        if (evt.getKeyCode() == 67 && la == 1) {
            la = 0;
            BuscarCliente b = new BuscarCliente();
            b.SetVenda(this);
            b.SetTipo(0);
            b.show();
        }

        //Para adicionar um produto
        if (evt.getKeyCode() == 80 && la == 1) {
            la = 0;
            BuscarProduto b = new BuscarProduto();
            b.SetTipo(1);
            b.SetSaidaVenda(this);
            b.show();
        }

        //Para finalizar a venda completa
        if (evt.getKeyCode() == 70 && la == 1) {
            la = 0;
            FinalizarTotal();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLNVenda;
    private javax.swing.JLabel jLQtd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTCliente;
    private javax.swing.JTextField jTEndereco;
    private javax.swing.JTextField jTPreco;
    private javax.swing.JTextField jTProduto;
    private javax.swing.JTextField jTQtd;
    private javax.swing.JTextField jTQtd_est;
    private javax.swing.JTextField jTTotalg;
    private javax.swing.JTextField jTValor;
    private javax.swing.JTable jTVendas;
    // End of variables declaration//GEN-END:variables

    //Cria o relatorio da nota
    private void relatorio() {
        Date data = new Date();

        int ano = data.getYear() + 1900;
        int dia = data.getDate();
        int mes = data.getMonth() + 1;
        String dias = null, mess = null;
        if (dia < 10) {
            dias = "0" + dia;
        } else {
            dias = "" + dia;
        }
        if (mes < 10) {
            mess = "0" + mes;
        } else {
            mess = "" + mes;
        }
        String nome = "NOTA_VENDA_N_" + idnota;
        String arquivo = nome;

        ConexaoRel con = new ConexaoRel();

//diretorio que vai salvar
        File dir = new File("c:/SGE");
        if (!dir.exists()) {
            dir.mkdir();
        }
        File l = new File("c:/SGE/Relatorios");
        if (!l.exists()) {
            l.mkdir();
        }
        File li = new File("c:/SGE/Relatorios/NotasVendas");
        if (!li.exists()) {
            li.mkdir();
        }

        String MostrarRelatorio;
        String path = "c:/SGE/Relatorios/NotasVendas/";
        try {
            con.conecta();
            con.executeSQL("select saida.*, produto.*, venda.*, cliente.*, funcionario.nome_fun from  saida, produto, venda, cliente, funcionario where saida.id_s=" + idnota + " and saida.id_s=venda.id_s and venda.id_p=produto.id_p and saida.id_c=cliente.id_c and funcionario.id_fun=saida.id_fun;");

            JRResultSetDataSource jrRS = new JRResultSetDataSource(con.resultset);
            //referencia o jasper
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("/Jasper/NotaVenda.jasper"), new HashMap(), jrRS);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            jv.setTitle("Nota de Venda - .: SGE :.");
            jv.setIconImage(new ImageIcon(getClass().getResource("/Imagens/icon-controle-de-estoqu.png")).getImage());
            jv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            // JasperViewer.viewReport(jp,true);
            File arq = new File(path + arquivo + ".pdf");
            if (arq.exists()) {
                int result = JOptionPane.showConfirmDialog(null, "O relatório " + arquivo + ".pdf já existe.\n Dezeja substitui-lo?", "SGE", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_NO_OPTION) {
                    JasperExportManager.exportReportToPdfFile(jp, path + arquivo + ".pdf");
                    MostrarRelatorio = path + arquivo + ".pdf";
                    JOptionPane.showMessageDialog(null, "Operação Realizada com sucesso!\n Salvo em: " + path + arquivo + ".pdf", "SGE", JOptionPane.INFORMATION_MESSAGE);
                    try {
                        Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL " + MostrarRelatorio);
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(null, "Erro ao acessar arquivo! \n\r ERRO:" + e.getStackTrace(), "SGE", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JasperExportManager.exportReportToPdfFile(jp, path + arquivo + ".pdf");
                MostrarRelatorio = path + arquivo + ".pdf";
                JOptionPane.showMessageDialog(null, "Operação Realizada consucesso!\n Salvo em: " + path + arquivo + ".pdf", "SGE", JOptionPane.INFORMATION_MESSAGE);
                try {
                    Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL " + MostrarRelatorio);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Erro ao acessar arquivo! \n\r ERRO:" + e.getMessage(), "SGE", JOptionPane.ERROR_MESSAGE);
                }

            }
        } catch (HeadlessException | JRException erro) {
            JOptionPane.showMessageDialog(null, "Erro!" + erro, "SGE", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
